ghi
The output handling code is designed to deal with the results of errors.
Issue: stephencelis/ghi#233
=> Supress stty error messages

ghi, lib/ghi/formatting.rb
When commenting, the first line does not become the title. This is erroneous
and misleading, although it does apply to `ghi open`, which is defined elsewhere.
I suspect this was a copy paste. This PR fixes this issue.
=> Remove errant comment in `ghi comment`

README.markdown
I also removed the `$ ` from the shell lines so that copy/paste would work as expected with sloppy mouse selection.
closes #222
=> update readme to support cygwin too

ghi, lib/ghi/commands/list.rb, lib/ghi/formatting.rb
Gives the ability to pass in an `organization` argument and view issues for all repos beneath that Org, provided you are authorized.
We use this daily for our company, across several repos this is a major time-saver.
=> Feature org issue listing

lib/ghi/authorization.rb
The original code showed github.com URL even though github.host is configured to another one.
=> Navigate to the actual setting URL for Github Enterprise

lib/ghi/formatting.rb
This fixes a bug when in 'truncate' reserved is higher than 'columns'. This would launch an exception, so that 'ghi list' would returs an empty list
=> Fix a bug in formatting.rb

lib/ghi/commands/open.rb
Add a config option `ghi.infer-issue` that, if set to "false", will
disable inferring the issue from the branch prefix
Fixes #198
=> Add config option to disable inferring issue

lib/ghi/authorization.rb
Now a ghi token is stored in https://github.com/settings/tokens . (not in https://github.com/settings/applications)
refs: https://github.com/stephencelis/ghi/issues/189#issuecomment-138334785
=> Change a message when a ghi token already exists

ghi, lib/ghi/commands/assign.rb, lib/ghi/commands/edit.rb
When you `unassign`, `assigns[:assignee].sub!` raises `NoMethodError` because `assigns[:assignee]` is `nil`.
So It needs to check for nil.
The error was like:
```
/Users/usp/bin/ghi:2917:in `execute': undefined method `sub!' for nil:NilClass (NoMethodError)
from /Users/usp/bin/ghi:2762:in `execute'
from /Users/usp/bin/ghi:91:in `execute'
from /Users/usp/bin/ghi:4285:in `<main>'
```
When you `unassign`, ghi sends `false` for `assignee` while github doesn't allow `false` for `assignee` but rather `null`.
So I assigned `nil` when `assignee` is `false`.
The error was like:
```
Invalid request.
For 'properties/assignee', false is not a string or null.
```
---
Thanks. :smile: :sushi:
=> Fix issues where unassign command fails.

ghi, lib/ghi/commands/list.rb, lib/ghi/formatting.rb
There have been a few requests for an option to prevent printing labels
when listing issues. If the list of issues involves a lot of labels, it
leads to truncation of issue titles. To make it easier to visually parse
lists like this, I've added a `--no-labels` option to `ghi-list` to
skip printing labels in the pager. Closes #259.
=> Add --no-labels option to `ghi-list`

ghi, lib/ghi/formatting/colors.rb
If `ghi` was installed via Homebrew before pygments.rb was added as a
dependency, the check for pygments being installed never gets run. It
looks like there was intention to rescue that `require` statement but
because `LoadError` doesn't inherit from `StandardError`, the exception
was uncaught and `ghi` would silently exit. This only seems to happen
currently on issues that include fenced code blocks, but I provided
reproducible evidence in #281. Merging this will fix #281, but I have
two concerns about the fact that pygments.rb was included as a
dependency in the first place:
1. Homebrew doesn't install Ruby gems for you, so this has to be done
manually. Attempting to `brew install ghi` without first having run
`gem install pygments.rb` just outputs an error and doesn't finish.
2. Most …
=> Fix uncaught LoadError requiring pygments.rb

ghi, lib/ghi/editor.rb, lib/ghi/formatting.rb
As discussed in #286. Use `` instead of `#` for the trailing comments.
=> Use markdown style comments for trailing message

ghi, lib/ghi/commands/comment.rb, lib/ghi/commands/edit.rb, lib/ghi/commands/milestone.rb, lib/ghi/commands/open.rb
Change the file extension of temporary files used for creating/editing
issues,comments and milestones to md(markdown).  The editor will
recoganize that its a markdown file and use markdown syntax
highlighting.
=> Change file extension of temperory files to md

ghi, lib/ghi/client.rb, lib/ghi/web.rb
In lib/ghi/client.rb line 122 use 
`http = Net::HTTP::Proxy(proxy.host, proxy.port, proxy.user, proxy.password).new HOST, PORT`
instead of
`http = Net::HTTP::Proxy(proxy.host, proxy.port).new HOST, PORT`
=> Add support for proxy authentication

ghi, lib/ghi/client.rb, lib/ghi/commands/list.rb, lib/ghi/commands/show.rb
The `application/vnd.github.beta+json` media type has been
[deprecated](https://developer.github.com/v3/versions/) for quite some time. It's recommended that the actual API
version, v3, be used instead.
This had only a minor impact to GHI: in v3, the `"pull_request"` key of
an issue response is omitted for issues that are not also pull requests.
Previously, `"pull_request"` would still be present but empty.
Signed-off-by: David Celis <me@davidcel.is>
=> Use application/vnd.github.v3+json

ghi, lib/ghi/commands/command.rb
In #279, a user expressed confusion that `[ -- [<user>/]<repo> ]` as a
command suffix is actually global and can be used with any command. This
patch adds a helpful message to the warning "Not a GitHub repo" to
suggest either re-running the command from a GitHub repo, or using the
suffix.
Fixes #279.
Signed-off-by: David Celis <me@davidcel.is>
=> Add [ -- [<user>/]<repo> ] suffix to warning

ghi, lib/ghi.rb, lib/ghi/commands/command.rb
It turns out that either `$0` doesn't include `ARGV` like I thought it did, or that slicing `ARGV` up subsequently mutates `$0`. Either way, I've modified GHI to store the full command being run so that the warning printed when not in a GitHub repo is more accurate.
Signed-off-by: David Celis <me@davidcel.is>
=> Fix GitHub repo warning

ghi, lib/ghi/client.rb
When repo is renamed and we use the old url for api call, the response
is Net::HTTPTemporaryRedirect and it contains the currosponding new url.
Fixes #267.
Before testing this, merge #298 because of #299 .
Or you can test this version which I merged
https://github.com/shubhamshuklaer/ghi/blob/repo_renaming_test/ghi
=> Handle case when repo is renamed but upstream url not updated

ghi, lib/ghi/web.rb
URI.parse is able to handle empty string("") as uri but not nil. Fixes #296
=> Check if proxy_uri is nil before parsing

lib/ghi/commands/list.rb, lib/ghi/formatting.rb
Hey guys, i am opening this pull request to add the issues list by milestone.
With this implementation, closed milestones with open issues will be listed and open milestones without open issues, will not be listed (i would like to know if this is the right behavior).
=> List issues by milestone

README.md, Rakefile, ghi, lib/ghi/commands.rb, lib/ghi/commands/help.rb, lib/ghi/commands/lock.rb, lib/ghi/commands/unlock.rb, man/ghi.1, man/ghi.1.html, man/ghi.1.ronn
A while back, I [added support for locking and unlocking issues via the API](https://developer.github.com/changes/2016-02-11-issue-locking-api/). This underwent a lengthy preview period that, as of today, [is over](https://developer.github.com/changes/2016-06-22-issue-locking-api-is-now-official/).
With the preview media type no longer required in the `Accept` header, I thought I'd go ahead and quickly add the commands `ghi lock` and `ghi unlock`. These are both fairly straightforward commands, though I did keep the `-m` option that's also present on `ghi close` to provide a comment before locking (or unlocking) the given issue.
Signed-off-by: David Celis <me@davidcel.is>
=> Add `ghi lock` and `ghi unlock` commands
